version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/apocalipcy
      - JWT_SECRET=your_jwt_secret_key_here_change_this_in_production
      - HUGGING_FACE_API_KEY=your_hugging_face_api_key_here
    depends_on:
      - mongo
      - ollama
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=apocalipcy
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
  ollama_data: 